### ISSUE TITLE
transport header missing for multiple messages?

### ISSUE THREAD

**Issue by Deeborg** [libyal/libpff#101]
Hi Team, 
transport_header returns none for most of the messages in pst file. I checked those messages manually and compared those to where transport headers are being read and I do not see any difference between them. Could you please help?
I have attached screenshot of one of the mails which was giving None when extracting transport headers for your reference. 

![image](https://user-images.githubusercontent.com/52920067/121395202-ca72b500-c96f-11eb-9406-55c06025ed72.png)

**Comment by Deeborg** [comment]
All I am looking for from header is sender address, recipient address, cc, bcc. Is there any alternative to get them? I could find only sender_name function in message class. Had no luck with others.

**Comment by joachimmetz** [comment]
@Deeborg pff is a MAPI value database, it really depends from version to version what MAPI values are stored and which not. You'll have to do the research which values are stored in your file and which not e.g. pffexport has multiple modes here that can help you.

Also since you mention None, pypff has not yet been completed also see https://github.com/libyal/libpff/issues/2

**Comment by Deeborg** [comment]
Looks like the problem is with encoding. Those messages encoded with UTF-8 are being read. Others with western European are returning None. I have also noticed few messages where headers are not displayed when I go to message properties and encoding information is not available for these messages.

**Comment by joachimmetz** [comment]
Can you provide a sample file or debug output https://github.com/libyal/libpff/wiki/Troubleshooting#verbose-and-debug-output. PFF and MAPI after all are proprietary, partially documented, formats

**Comment by Deeborg** [comment]
Please download sample pst from below link 
https://drive.google.com/file/d/1otTielU_uHntcVENUMtk5BTkFWTyIhsK/view?usp=sharing

Is there any other way to extract recipient, cc and bcc details?
message class has only sender_name.

**Comment by joachimmetz** [comment]
you could get the raw MAPI values

**Comment by joachimmetz** [comment]
> Please download sample pst from below link

thx I'll have a look as soon as time permits

**Comment by Deeborg** [comment]
> > Is there any other way to extract recipient, cc and bcc details?
> 
> you could get the raw MAPI values

Thanks! That would totally solve my problem. I would appreciate if you could help me get MAPI values with pypff. I went through the source and am unable to find it.

**Comment by joachimmetz** [comment]
Try `record_entry.get_data()` https://github.com/libyal/libpff/blob/main/pypff/pypff_record_entry.c#L54

**Comment by Deeborg** [comment]
record_entry works on what object? Or rather how do I create record_entry object?

**Comment by Deeborg** [comment]
Got everything to work as required. Thanks for this amazing library and the support!!

**Comment by Mahesh210182** [comment]
Hi Deeborg, Could you please guide how you extracted From, to, subject data from the get_data method.

**Comment by luckman212** [comment]
@Deeborg Would you be so kind as to post your working code? I am struggling to extract some email addresses (sender/recipient) from a PST...

**Comment by MaheshE99ME25** [comment]
@luckman212

https://gist.github.com/MaheshE99ME25/2317c5c7302f843ebddbf42f5eea1358

**Comment by SjoerdHilhorst** [comment]
[A working example](https://gist.github.com/SjoerdHilhorst/6956b48a0d75931bcb5831c07f44a020) on how to obtain email adresses from pst file using raw MAPI values
