### ISSUE TITLE
Encoding error

### ISSUE THREAD

**Issue by CraftedCat** [libyal/libpff#105]
Hi, guys!

I have some problem with encodings

6-5. PR_앨리슨
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\logging\__init__.py", line 1028, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\Python37\lib\encodings\cp1251.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 61-63: character maps to <undefined>

how to fix?

**Comment by joachimmetz** [comment]
@CraftedCat based on the output this is not an issue related to libpff (or pypff). If you think this is issue related to libpff, please take the time to write a more detailed report. Closing and marking as invalid
