### ISSUE TITLE
FR: Have libpff_attachment_get_type support attachment method 0

### ISSUE THREAD

**Issue by jengelh** [libyal/libpff#107]
PST files can have attachment method 0.
![noatt](https://user-images.githubusercontent.com/8861948/153408004-b8a70f54-73d8-4f17-8f4f-57b0c78e0dcf.png)
`libpff_attachment_get_type` should not fail in this case.

**Comment by joachimmetz** [comment]
@jengelh do you have sample file what is in the NO_ATTACHMENT object so the documentation can be updated accordingly

**Comment by jengelh** [comment]
[107.zip](https://github.com/libyal/libpff/files/8042398/107.zip)

**Comment by joachimmetz** [comment]
Changes in https://github.com/libyal/libpff/commit/56114a3eed56170046b848a42946ebf4f42fef04
