### ISSUE TITLE
Does libpff support recovery of hard deleted items from 64-bit or 64-bit with 4k page ost files ?

### ISSUE THREAD

**Issue by zy-ph** [libyal/libpff#111]

**Comment by joachimmetz** [comment]
@zy-ph can you be more specific, what do **you** mean with "hard deleted items" ?

**Comment by zy-ph** [comment]
The items recovered when you use pffexport -m recovered

**Comment by joachimmetz** [comment]
@zy-ph I have no idea what you mean, I cannot your answer without being to understand what you mean. Closing.
