### ISSUE TITLE
Is there a way to get the encoding for html_body?

### ISSUE THREAD

**Issue by gwiedeman** [libyal/libpff#112]
Currently the `.html_body` attribute for a `pypff.message` object returns a bytestring of the message body. However, messages may have a variety of encodings. Is there some way of accessing the encoding for each message body so it may be reliably decoded?

I understand that this is still a work in progress, and I appreciate the lack of time, so I'm not expecting a fix if this is yet to be implemented, but I wanted to make sure there wasn't an approach that I was missing. The `.record_sets` attribute seems to potentially have data, but these also appear to be bytestrings which seems to run into the same issue.

Thanks for all the work done so far!

**Comment by joachimmetz** [comment]
This encoding occurs on the MAPI level not on the PFF database level. Have a look at my notes https://github.com/libyal/libfmapi/blob/main/documentation/MAPI%20definitions.asciidoc#61-the-message-body
