### ISSUE TITLE
unable to retrieve sub message

### ISSUE THREAD

**Issue by HusImran** [libyal/libpff#113]
Hi There,

I am using Python and Pypff - version 20211114
I am reading a PST file and trying to get the delivery date for each item. However, I run into the below error:

pypff_folder_get_sub_message_by_index: unable to retrieve sub message: 4554 type. libpff_table_read_entry_value: unsupported value type: 0x00000052 with value size: 4.  libpff_table_read_bc_record_entries: unable to read entry value: 210.  libpff_table_read_bc_values: unable to read table record entries.  libpff_table_read_values: unable to read bc table values.  libpff_table_read: unable to read table values.  libpff_item_values_read: unable to read table.  libpff_item_values_get_record_entry_by_type: unable to read item values.  libpff_internal_item_determine_type: unable to retrieve record entry: 0x001a.  libpff_item_get_type: unable to determine item type.

Please can I have some help in understanding why this is happening?

Many thanks!

**Comment by joachimmetz** [comment]
Python bindings are WIP also see https://github.com/libyal/libpff/issues/2

> libpff_table_read_entry_value: unsupported value type: 0x00000052 with value size: 4. 

Looks like an unsupported format case. Have a look at https://github.com/libyal/libpff/wiki/Troubleshooting#verbose-and-debug-output to troubleshoot format issues.

**Comment by joachimmetz** [comment]
No additional input from original reporter, insufficient information to address issue, closing
