### ISSUE TITLE
LIBPFF_MESSAGE_FLAG_READ

### ISSUE THREAD

**Issue by lfern** [libyal/libpff#114]
Hi, please, how could I get if a message is read? I can see there is a flag, LIBPFF_MESSAGE_FLAG_READ, but I am not sure how to use it to check if a message is read or unread.

Thanks!

**Comment by joachimmetz** [comment]
pff is MAPI container format, have a look at which MAPI type represents this information https://github.com/libyal/libfmapi/blob/main/documentation/MAPI%20definitions.pdf
