### ISSUE TITLE
Not able to download Screenshot images which were added in email body also not able to download .msg file

### ISSUE THREAD

**Issue by jitdwoodside** [libyal/libpff#118]
I am trying to download attachments from pst file but not able to download the screenshots pasted in the body of email using snipping tool. Also not able to download attachments with .msg extension. 
Sample code 
for index,eachattachment in enumerate(eachitem.attachments):
            for attachment_entry in eachattachment.get_record_set(0).entries:
                if attachment_entry.entry_type == 12289:
                    print(attachment_entry.data_as_string)
In this code I am trying to get the filename for screenshot and .msg files, but i am getting this thing as output "Picture (Device Independent Bitmap)" and "Global Message:" How to download this attachment? Please help.

**Comment by joachimmetz** [comment]
Per https://github.com/libyal/libpff/issues/2 Python bindings are WIP
