### ISSUE TITLE
Questions about the library

### ISSUE THREAD

**Issue by rourion** [libyal/libpff#12]
Hello -- I've built the Python bindings per documentation and have been familiarizing myself with pypff capabilities. I cannot find a way to do some tasks I'd like to and I'm not sure if it is because the library does not support the specific operations or because I am unfamiliar with it.

  Specifically, I'd like to read the unique ID for every message in a PST (the 'StoreID') and identify the names or, better yet, metadata of any message attachments. Thank you for any information you can share regarding these questions.

**Comment by joachimmetz** [comment]
So pypff is still work in progress (also see: https://github.com/libyal/libpff/issues/2) I basically lack the time at the moment, but still planning to complete it and get it used into another project I'm involved with.

So a pst file is basically a MAPI database and for more info on MAPI values see (https://googledrive.com/host/0B3fBvzttpiiSRlR1QkU5Vk43ZWs/MAPI%20definitions.pdf)

**Comment by rourion** [comment]
I understand, thank you for all your efforts. I will look at your resource and familiarize myself with the data structure.
