### ISSUE TITLE
OSError: pypff_message_get_html_body: unable to retrieve HTML body size

### ISSUE THREAD

**Issue by woheme-c** [libyal/libpff#120]
Thanks for this interesting lib. amazing work. I was looking for a solution but just cant find something constructive. Some days before it was possible to extract information out of a huge amount of .pst-files. Now I get this error:

OSError: pypff_message_get_html_body: unable to retrieve HTML body size. libpff_message_get_html_body_size: missing value data.

Or maybe somebody has a hint for a solution. I just get crazy. :D cant solve it. 

Thanks

PS. Version: libpff-python==20211114

**Comment by joachimmetz** [comment]
Python bindings are WIP see, https://github.com/libyal/libpff/issues/2

Closing this issue as a duplicate

**Comment by woheme-c** [comment]
Thans for your answer. Unfortunately I don´t get it. Is this a well known problem or something you didnt build in (wip)? If it is a known problem, than maybe you know the reason? So I think I can fix it on my self if you have something like an idea about the reason of the bug. There was this chenese guy, that had some similar problems, but he unfortunatelly didn´t reply and you closed the issue.

**Comment by joachimmetz** [comment]
> Unfortunately I don´t get it. Is this a well known problem or something you didnt build in (wip)?

The binding is not completed, there is no guarantee that is should work. I recommend waiting for it to be completed or help out completing it.

> There was this chenese guy, that had some similar problems, but he unfortunatelly didn´t reply and you closed the issue.

Unfortunately my time is very limited and duplication of issues unfortunately creates additional maintenance overhead.

**Comment by woheme-c** [comment]
I would like to help out to completed but need somethin like a hint, what kind of source of failure that can be. Because it is a realy nice and usefull project.

**Comment by joachimmetz** [comment]
The hint (back trace) is

```
OSError: pypff_message_get_html_body: unable to retrieve HTML body size. libpff_message_get_html_body_size: missing value data.`
```

You can use the tooling or verbose/debug output and documentation to analyze the actual data.
