### ISSUE TITLE
problems when switching to new version

### ISSUE THREAD

**Issue by woheme-c** [libyal/libpff#124]
I have changed pypff to the new version "libpff-python 20231205" and suddenly I get various errors in my application. I developed my application with the previous "libpff-python 20211114" ... version.  

One error concerns the sub_messages: 

OSError: pypff_folder_get_number_of_sub_messages: unable to retrieve number of sub messages. libpff_data_array_read_entries: unable to find data identifier: 656588. libpff_table_read_descriptor_data_list: unable to read data array entries. libpff_table_values_array_get_value_data_by_entry_number: unable to read descriptor: 63 data: 40492198 list. libpff_table_read_values_array: unable to retrieve record entry values data for index: 1. libpff_table_read_7c_values: unable to read values array. libpff_table_read_values: unable to read 7c table values. libpff_table_read: unable to read table values. libpff_item_values_read: unable to read table. libpff_folder_determine_sub_messages: unable to read descriptor identifier: 8590. libpff_folder_get_number_of_sub_messages: unable to determine sub messages.

Another error concerns the attachments:

pypff_message_get_attachments: unable to retrieve number of attachments. libpff_local_descriptors_node_get_entry_data: invalid local descriptors node. libpff_local_descriptors_get_value_by_identifier: unable to retrieve node entry: 0 data. libpff_local_descriptors_tree_get_value_by_identifier: unable to retrieve index value: 1649 from index. libpff_table_get_local_descriptors_value_by_identifier: unable to retrieve local descriptor identifier: 1649. libpff_item_values_get_local_descriptors_value_by_identifier: unable to retrieve local descriptor identifier: 1649. libpff_message_determine_attachments: unable to retrieve local descriptor identifier: 1649. libpff_message_get_number_of_attachments: unable to determine attachments.

Has anyone already found a solution or some information about this errors?

Greetings

**Comment by joachimmetz** [comment]
As indicated in https://github.com/libyal/libpff/issues/2 Python bindings are work in progress.

**Comment by trb** [comment]
Just to clarify - the python bindings have been WIP since 2014 and could break with any update and therefore should not be used? I ran into the same breaking issue regarding attachments after a updating from 20211114 to 20231205 and nothing indicated that I should expect the bindings to just stop working.

**Comment by joachimmetz** [comment]
>  the python bindings have been WIP since 2014 and could break with any update and therefore should not be used? 

And they will remain that way until I have time to work on it. Or if you need them urgently fixed I recommend hiring someone to fix them for you.

> I ran into the same breaking issue regarding attachments after a updating from 20211114 to 20231205 and nothing indicated that I should expect the bindings to just stop working.

my point is there is nothing indicating for you expect the bindings to be working in the first place

**Comment by trb** [comment]
Hiring someone is going to take too long, I can't do a release right now. I can't postpone releases until I find a developer to fix this issue.

> my point is there is nothing indicating for you expect the bindings to be working in the first place

Maybe mention it on the docs page? https://github.com/libyal/libpff/wiki/Python-development
I admit I missed the alpha status on the pypi package, that's on me. I'll go find another solution to deal with pst files.
