### ISSUE TITLE
How to export emails from a PST file to EML format?

### ISSUE THREAD

**Issue by jsuto** [libyal/libpff#132]
I can't find cli arguments for pffexport to extract EML files from a PST. Is it possible to do?
I have pffexport 20231205.

**Comment by joachimmetz** [comment]
what specific format do you mean with EML?

**Comment by joachimmetz** [comment]
Not all PST/OST content is RFC-2822 compatible and the pfftools are not intended to export data in a lossy wat. Closing as infeasible
