### ISSUE TITLE
After compiling pypff, would you please to say where is the source code?

### ISSUE THREAD

**Issue by wang178743010** [libyal/libpff#18]
I am using pypff library, found the methods of extracting email attachments without, only extract to the number of accessories, to help me, all the source code of the library.Where can I find to!

**Comment by wang178743010** [comment]
The recipient Didn't get to，Both methods can't find it...Save me........

**Comment by joachimmetz** [comment]
Python bindings are still work in progress per: https://github.com/libyal/libpff/issues/2
