### ISSUE TITLE
Cygwin Python Bindings Problem

### ISSUE THREAD

**Issue by cvaughan79** [libyal/libpff#20]
I'm a big fan of this project as it's allowing me to perform a few functions that I've wanted to for years - so thanks for the hard work. 

 I can utilise the Python bindings in Ubuntu without any problems whatsoever but I can't get beyond the  './configure' stage with Cygwin.  All of the prerequisite libraries and Python are present when I try and run it but when I run './configure' I get these messages, which appear to indicate that Python won't be happening:-

checking whether to enable build Python bindings... (cached) no
checking whether to use use to specify the Python directory (pythondir)... (cached) no
checking whether to enable build Python 2 bindings... (cached) no
checking whether to use use to specify the Python 2 directory (pythondir2)... (cached) no
checking whether to enable build Python 3 bindings... (cached) no
checking whether to use use to specify the Python 3 directory (pythondir3)... (cached) no

Features:
   Multi-threading support:                  pthread
   Wide character type support:              no
   pfftools are build as static executables: no
   Java (jpff) support:                      no
   Python (pypff) support:                   no
   Python version 2 (pypff) support:         no
   Python version 3 (pypff) support:         no
   Verbose output:                           no
   Debug output:                             no

When I 'make install' pffexport does not compile either.  I don't know if this is linked? 

Are you able to provide any advice please?

**Comment by joachimmetz** [comment]
Per: https://github.com/libyal/libpff/issues/1 this is work in progress
