### ISSUE TITLE
Accessing message header attributes using pypff

### ISSUE THREAD

**Issue by jfaganUK** [libyal/libpff#21]
I am using pypff. I have a PST archive with 10,000 messages from a variety of senders. I want to be able to get the header information from each of the messages (the to/from/cc/bcc, the date, the thread-index, message id, etc). I can get the subject and body of the message using the message object, but I can't seem to access anything else. Is there an API for these other message properties?

**Comment by joachimmetz** [comment]
per https://github.com/libyal/libpff/issues/2 pypff is WIP
