### ISSUE TITLE
Compiling fails because HAVE_UNLINK is undefined

### ISSUE THREAD

**Issue by rdvdijk** [libyal/libpff#22]
Running `./synclibs.sh` and `./autogen.sh` results in the following error:

```
libcfile_support.c:742:2: error: #error Missing file remove function
 #error Missing file remove function
  ^
make[1]: *** [libcfile_support.lo] Error 1
make: *** [all-recursive] Error 1
Running: 'make' failed
```

Line 688 in `libcfile/libcfile_support.c`:

```c
#elif defined( HAVE_UNLINK )
```

The `libcfile` source defines `HAVE_UNLINK` in `common/config.h`, which is not checked out by `synclibs.sh`, so the compiler fails on line 742.

**Comment by joachimmetz** [comment]
>  so the compiler fails on line 742.

Technically its the [C preprocessor](https://en.wikipedia.org/wiki/C_preprocessor) that fails as intended.

This is pending a source update, when time permits. In the mean time you could replace libcfile.m4 with the [latest version](https://github.com/libyal/libyal/blob/master/data/m4/libcfile.m4).

**Comment by joachimmetz** [comment]
Source updated: https://github.com/libyal/libpff/commit/e0882a80cce79c11599f83943c00c9419eaacfe4
