### ISSUE TITLE
Provide a new release

### ISSUE THREAD

**Issue by udgover** [libyal/libpff#24]
Hello Joachim,

Is it possible to provide a release for libpff? Indeed debian forensics maintainers rely on your release to package libyal packages. As you can see on their [package overview page](https://qa.debian.org/developer.php?login=forensics-devel@lists.alioth.debian.org) libpff package is based on 20120802-5 release when it was available through gdrive I guess...

Thanks

**Comment by joachimmetz** [comment]
I'll look into to this, but alas my available time is limited.

**Comment by joachimmetz** [comment]
Just pushed an experimental pre-release.
https://github.com/libyal/libpff/releases/tag/20161119

**Comment by udgover** [comment]
That was fast! Thanks. I'm going to test soon.
