### ISSUE TITLE
Getting started for use libpff

### ISSUE THREAD

**Issue by kiquenet** [libyal/libpff#28]
I'm newbie, not python knowledge.

1) any good Getting started for use libpff ? 

2) And a full sample for read OST (Offline Storage Table) ?

3) Powershell scripts in this project ? Powershell and OST?

**Comment by joachimmetz** [comment]
> I'm newbie, not python knowledge.

libpff is written in C not in Python.

> 1) any good Getting started for use libpff ?

any good what?

> 2) And a full sample for read OST (Offline Storage Table) ?

No

> 3) Powershell scripts in this project ?

PS scripts are for building on Windows https://github.com/libyal/libpff/wiki/Building,

> Powershell and OST?

No

**Comment by kiquenet** [comment]
I have Microsoft Visual Studio 2013 adn 2015.

I need:

the contents of the zlib source distribution package

To compile the pypff Python-bindings, we need install Python in Windows

Really, install python in Windows.

When I execute msbuild and I get the final compilation, then I get the C dll, that I can use DllImport in my C# code for try read OST file.

**Comment by joachimmetz** [comment]
Described here: 
https://github.com/libyal/libpff/wiki/Building#using-microsoft-visual-studio
