### ISSUE TITLE
Does it support x64? My test program crashed in x64.

### ISSUE THREAD

**Issue by fzusad** [libyal/libpff#29]
Hello Joachim,
I used it in Visual Studio 2008,my test program parsed PST file successfully in x86. However,it crashed in x64.
It seems to occured at `internal_record_entry = (libpff_internal_record_entry_t *) record_entry;` in **libpff_record_entry_get_value_utf8_string_size()**.

Looking forward to your replay.

**Comment by joachimmetz** [comment]
It should work on both x86 an x64 ? Can you provide me with more details such as

* a stacktrace of the crash
* description of the crash, error, segfault, etc ?

**Comment by fzusad** [comment]
The stacktrace:
![stacktrace](https://cloud.githubusercontent.com/assets/17847376/19957427/94ea1d26-a1d1-11e6-9435-ab56a1cfad06.png)

The final break in here in libuna_utf8_string_size_from_utf16_stream().
`	if( ( utf16_stream[ 0 ] == 0xfe )
	 && ( utf16_stream[ 1 ] == 0xff ) )
	{
		read_byte_order    = LIBUNA_ENDIAN_BIG;
		utf16_stream_index = 2;
	}`
The utf16_stream is neither null nor a valid pointer,so the program crashed.When i traced it, i found the address of utf16_stream[ ] is 0x000000000000000e. it is illegal.

**Comment by joachimmetz** [comment]
I'll have a closer look as part of https://github.com/libyal/libpff/issues/3

**Comment by joachimmetz** [comment]
libuna_utf8_string_size_from_utf16_stream has recently been updated in libuna. Could you please have a look with the latest libuna and, if you were using libpff experimental, the latest experimental version as well. 

Marking as invalid seeing this looks like an issue in libuna (not in libpff). Closing for now but feel free to reopen if issue still persist.
