### ISSUE TITLE
Compilation issue since your last commit in libcerror

### ISSUE THREAD

**Issue by udgover** [libyal/libpff#30]
Since yesterday, it is impossible to compile libpff (and should be the same for most of libyal libraries). I did the usual following steps:

./synclibs.sh
./autogen.sh
./configure
make

and I'm getting the following errors:

libcerror_error.c:24:27: fatal error: narrow_string.h: No such file or directory
 #include <narrow_string.h>

After digging a bit, I found you [committed yesterday](https://github.com/libyal/libcerror/commit/600c9dfe4a7d2e05881cfaebd28a4823b6b73ea2) the following includes in libcerror_error.c

<narrow_string.h>
<system_string.h>
<wide_string.h>

located in common folder of libcerror but which are not available when doing synclibs.sh in libpff.

My current workaround is to rm -rf libcerror and clone from commit 78d9b41c9efacc169d9a259694e891e6257d23b2

Cheers!

**Comment by joachimmetz** [comment]
You'll have to wait until the code migration is done, also it is not recommended to "live on HEAD" unless you're actively developing libpff. Also see: https://github.com/libyal/libpff/wiki/Building#read-first.

**Comment by udgover** [comment]
Thanks for your quick reply, as always!

I know that I shouldn't "live on HEAD" but since there is no source distribution package in [downloads](https://github.com/libyal/libpff/releases) and [package for libpff in all Debian based distribution are from 2012](https://github.com/libyal/libpff/issues/24), I have to build packages directly from your github repository. 

Anyway, if others packagers are dealing with the same issues, I temporary fixed the problem until your code migration by resetting to first commit before 2016-11-01 just after the git clone command in synclibs.sh thiw way:

        cd ${LOCAL_LIB}-$$
        git reset --hard `git rev-list -n 1 --before="2016-11-01" master`
        cd ..

Looking forward to downloading your new release ;)

**Comment by joachimmetz** [comment]
> Looking forward to downloading your new release ;) 

I see, working on it when time permits.
