### ISSUE TITLE
Question about libpff_folder_get_type

### ISSUE THREAD

**Issue by yangmtb** [libyal/libpff#31]
line 111, column 15
it's LIBPFF_ENTRY_TYPE_CONTAINER_CLASS , 
should be LIBPFF_ENTRY_TYPE_FOLDER_TYPE?

**Comment by joachimmetz** [comment]
Why do you think this is a bug?

**Comment by yangmtb** [comment]
the function name is folder type, so i think it should be LIBPFF_ENTRY_TYPE_FOLDER_TYPE
by the way, how can i distinguish attachment, about inline or attachment.?
how can i get content-id with inline picture, Think you

**Comment by joachimmetz** [comment]
> the function name is folder type, so i think it should be LIBPFF_ENTRY_TYPE_FOLDER_TYPE
by the way

nope that assumption is not correct, the terminology used by libpff is not that of MAPI.
see the MAPI documentation for the difference between PidTagFolderType and PidTagContainerClass

> how can i get content-id with inline picture

libpff exposes the MAPI values, check the MAPI and MSDN documentation on how to piece back together a message
