### ISSUE TITLE
fatal error: 'pff_test_libcnotify.h' file not found

### ISSUE THREAD

**Issue by taktikal17** [libyal/libpff#34]
Hi @joachimmetz , 

I got an error by trying to install libpff-experimental-20161119.tar

MacOs Sierra, v10.12

What I did:
1. download 'libpff-experimental-20161119.tar'
2. tar xfv libpff-experimental-20161119.tar
3. cd libpff-20161119
4. CFLAGS="-isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -arch x86_64 -arch i386" \
5. LDFLAGS="-Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -arch x86_64 -arch i386" \
6. ./configure --enable-python
7. make
8. make install
9. cd tests
9. make check

=> Error:
pff_test_deflate.c:32:10: fatal error: 'pff_test_libcnotify.h' file not found
#include "pff_test_libcnotify.h"
         ^
1 error generated.
make[1]: *** [pff_test_deflate.o] Error 1
make: *** [check-am] Error 2

Is there another way to use the library or another source to use?
Thank you!

**Comment by joachimmetz** [comment]
I'll have a look when time permits, could be a bug in the experimental version.

> Is there another way to use the library or another source to use?

Use the last alpha version: https://github.com/libyal/legacy/tree/master/libpff

**Comment by joachimmetz** [comment]
This is a bug in the tests, should not stop you from being able to use the library.

**Comment by joachimmetz** [comment]
Fixed in https://github.com/libyal/libpff/commit/2d884ff445b56a341169356c39845e49ba90c8d1
