### ISSUE TITLE
Narrow string function being called instead of wide version

### ISSUE THREAD

**Issue by SammyB428** [libyal/libpff#40]
https://github.com/libyal/libpff/blob/master/pfftools/export_handle.c#L3376

Should be a call to libpff_record_entry_get_data_as_utf16_string instead of libpff_record_entry_get_data_as_utf8_string.

As it stands, a UTF8 (narrow) string will get concatenated to a UTF16 (wide) string to produce a folder name that looks like Chinese. Mixes wide and narrow characters.

**Comment by joachimmetz** [comment]
thx for reporting I'll have a look as soon as time permits.

**Comment by joachimmetz** [comment]
Duplicate of https://github.com/libyal/libpff/issues/47, but issue is fixed now.
