### ISSUE TITLE
libpff_name_to_id_map.c:687:8: error: use of undeclared identifier 'libfmapi_guid_public_strings'  

### ISSUE THREAD

**Issue by smclinden** [libyal/libpff#42]
Since the OS X toolchain wasn't working, I decided to build the required libraries manually. Compilation worked fine but when the latest libfmapi was added, libpff choked with the error, above.

**Comment by joachimmetz** [comment]
thx for the report, I'll have a look as soon as time permits

**Comment by joachimmetz** [comment]
Issue with libfmapi.m4
```
./configure: line 49341: AX_LIBFMAPI_CHECK_LIB: command not found
```

**Comment by joachimmetz** [comment]
Updates to libfmapi.m4 and libfmapi

**Comment by joachimmetz** [comment]
Tests on travis pass https://travis-ci.org/libyal/libpff/builds/403856889, closing issue
