### ISSUE TITLE
In pypff, at get _ * _ time, I fixed the error

### ISSUE THREAD

**Issue by kimtaehong** [libyal/libpff#46]
hi, I am reminded that I have fixed an error in the get _ * _ time function call.
When calling the libpff_message_get _ "_ time function inside the get _ * _ time function, it seems that an error occurred because an invalid parameter was passed as follows.
```c++
...
 result = libpff_message_get_delivery_time(
                         pypff_item->record_set,
	                 &filetime,
	                 &error );
...
```
So I fixed it as follows and it worked normally. If you have resolved the bug, please check again.
```c++
...
 result = libpff_message_get_delivery_time(
                         pypff_item->item,
	                 &filetime,
	                 &error );
...
```

And I'm wondering how to use attachments object calls. Currently it says that it should be called with attachments or get_attachment (index).

**Comment by joachimmetz** [comment]
made some changes in ee17d7c
