### ISSUE TITLE
Complete Internet Headers not written after around 200 emails

### ISSUE THREAD

**Issue by AniketBhadane** [libyal/libpff#50]
In folder.export\Root - Mailbox\IPM_SUBTREE\Inbox\, on opening messages after around 200, I can see that partial headers are present in Internet Headers text file. Why?

I'm running the program as: pffexport.exe -f all -m all -t folder file.ost

**Comment by joachimmetz** [comment]
what version of libpff / pffexport? what compiler was used to build it?

**Comment by AniketBhadane** [comment]
pffexport.exe -h shows following:
pffexport 20150106

**Comment by AniketBhadane** [comment]
The downloaded folder has name libpff_150106, which I got from a link in a stackoverflow answer.
This was already built by the author of the answer, using cygwin.

Also, pffexport.exe -h shows following:
pffexport 20150106

**Comment by joachimmetz** [comment]
20150106 is an old experimental version of libpff, I op to try the last alpha https://github.com/libyal/legacy/tree/master/libpff or the latest experimental https://github.com/libyal/libpff/releases

**Comment by AniketBhadane** [comment]
Which compiler is recommended?

**Comment by AniketBhadane** [comment]
I compiled the experimental release on Ubuntu 16.04.

I used following commands:
sudo ./configure
sudo make
sudo make install

But how do I run the program now? Where is the executable stored?

**Comment by joachimmetz** [comment]
`sudo make install` will install by default in /usr/local/bin/

**Comment by joachimmetz** [comment]
also there is no need to run `./configure` and `make` with `sudo`

**Comment by AniketBhadane** [comment]
It gives error:
pffexport: error while loading shared libraries: libpff.so.1: cannot open shared object file: No such file or directory

**Comment by joachimmetz** [comment]
Make sure /use/local/lib is in your library cache configuration (ld.conf)
and your library cache is up to date (ldconfig)

**Comment by AniketBhadane** [comment]
And after doing "make" in minsys-mingw, please can you tell where is the executable created?

**Comment by AniketBhadane** [comment]
I was able to compile and run the program. I still got the same problem. This was with OST from Outlook 2010. Then I used another OST from Outlook 2016. And complete headers for all emails are now written.

**Comment by joachimmetz** [comment]
And you are sure it is not an issue with the file? Any chance of you being
able to share the file or format debug information?

**Comment by AniketBhadane** [comment]
It might be a problem with OST file. Also, can the tool convert the OST files from different versions of Outlook equally?

**Comment by joachimmetz** [comment]
libpff just reads the MAPI database inside the OST files. You can dump the MAPI values with pffexport or have a look with https://github.com/stephenegriffin/mfcmapi

**Comment by joachimmetz** [comment]
No updates in a while closing issue
