### ISSUE TITLE
Error in exporting Outlook 'pst' file

### ISSUE THREAD

**Issue by kumartvm** [libyal/libpff#51]
Thank you for your effort in developing this library. And I would like to inform you some problems I faced.  I had built the experimental release in visual studio 2015 with no errors. And I ran the pffexport.exe from Release folder in command prompt and gave 'Sample.pst' file as argument. But It results following errors. 

 folder item 3 out of 10.
Exporting folder item 4 out of 10.
Exporting folder item 5 out of 10.
Exporting folder item 6 out of 10.
Skipped item 1 out of 1 of type: IPM.Microsoft.ScheduleData.FreeBusy.
Exporting folder item 7 out of 10.
Exporting folder item 8 out of 10.
Exporting folder item 9 out of 10.
Exporting folder item 10 out of 10.

Exporting recovered items.
Exporting folder item 1 out of 17.
Exporting folder item 2 out of 17.
Unable to retrieve type of item 3 out of 17.
libpff_table_read: unsupported table signature: 0x00.
libpff_item_values_read: unable to read table.
libpff_item_values_get_record_entry_by_type: unable to read item values.
libpff_item_determine_type: unable to retrieve record entry: 0x04I32x.
libpff_item_get_type: unable to determine item type.
export_handle_export_item: unable to retrieve item type.
Unable to retrieve type of item 4 out of 17.
libpff_data_block_read: mismatch in data size ( 16705 != 1568 ).
libpff_io_handle_read_descriptor_data_list: unable to read data block at offset:
 320576.
libpff_table_read: unable to read descriptor: 641 data: 8316 list.
libpff_item_values_read: unable to read table.
libpff_item_values_get_record_entry_by_type: unable to read item values.
libpff_item_determine_type: unable to retrieve record entry: 0x04I32x.
libpff_item_get_type: unable to determine item type.
export_handle_export_item: unable to retrieve item type.
Unable to retrieve type of item 5 out of 17.
libpff_table_read: unsupported table signature: 0x00.
libpff_item_values_read: unable to read table.
libpff_item_values_get_record_entry_by_type: unable to read item values.
libpff_item_determine_type: unable to retrieve record entry: 0x04I32x.
libpff_item_get_type: unable to determine item type.
export_handle_export_item: unable to retrieve item type.
Unable to retrieve type of item 6 out of 17.
libpff_table_read: unsupported table signature: 0x00.
libpff_item_values_read: unable to read table.
libpff_item_values_get_record_entry_by_type: unable to read item values.
libpff_item_determine_type: unable to retrieve record entry: 0x04I32x.
libpff_item_get_type: unable to determine item type.
export_handle_export_item: unable to retrieve item type.
Unable to retrieve type of item 7 out of 17.
libpff_table_read: unsupported table signature: 0x00.
libpff_item_values_read: unable to read table.
libpff_item_values_get_record_entry_by_type: unable to read item values.
libpff_item_determine_type: unable to retrieve record entry: 0x04I32x.
libpff_item_get_type: unable to determine item type.
export_handle_export_item: unable to retrieve item type.
Exporting folder item 8 out of 17.
Unable to export sub messages.
libpff_folder_get_sub_message: unable to retrieve sub message tree node.
export_handle_export_sub_messages: unable to retrieve sub message: 1 out of 1.
export_handle_export_folder: unable to export sub messages.
Exporting folder item 9 out of 17.
Unable to export sub messages.
libpff_folder_get_sub_message: unable to retrieve sub message tree node.
export_handle_export_sub_messages: unable to retrieve sub message: 1 out of 1.
export_handle_export_folder: unable to export sub messages.
Exporting email item 10 out of 17.
Exporting folder item 11 out of 17.
Unable to retrieve type of item 12 out of 17.
libpff_data_block_read: mismatch in data size ( 324 != 216 ).
libpff_io_handle_read_descriptor_data_list: unable to read data block at offset:
 325120.
libpff_table_read: unable to read descriptor: 524419 data: 8000 list.
libpff_item_values_read: unable to read table.
libpff_item_values_get_record_entry_by_type: unable to read item values.
libpff_item_determine_type: unable to retrieve record entry: 0x04I32x.
libpff_item_get_type: unable to determine item type.
export_handle_export_item: unable to retrieve item type.
Exporting folder item 13 out of 17.
Skipped item 14 out of 17 of type: IPM.MessageManager.
Skipped item 15 out of 17 of type: IPM.MessageManager.
Exporting email item 16 out of 17.
libpff_message_get_html_body_size: missing value data.
libpff_offsets_index_get_index_value_by_identifier: no recovered offsets index v
alues for identifier: 6516.
libpff_io_handle_read_descriptor_data_list: unable to find offset index value id
entifier: 6516.
libpff_table_read: unable to read descriptor: 1682 data: 6516 list.
libpff_item_values_read: unable to read table.
libpff_message_initialize_sub_item_recipients: unable to read recipients local d
escriptor identifier: 1682.
libpff_message_determine_recipients: unable to create sub item recipients.
libpff_message_get_recipients: unable to determine recipients.
export_handle_export_recipients: unable to retrieve recipients.
libpff_message_get_html_body_size: missing value data.
Exporting attachment 1 out of 1.
libpff_offsets_index_get_index_value_by_identifier: no recovered offsets index v
alues for identifier: 7202.
libpff_local_descriptors_tree_read: unable to retrieve offset index value identi
fier: 7202.
libpff_table_read: unable to read local descriptors tree with identifier: 7202.
libpff_item_values_read: unable to read table.
libpff_item_values_get_record_entry_by_type: unable to read item values.
libpff_internal_item_get_entry_value_32bit_integer: unable to retrieve record en
try: 0x04I32x 0x3705.
libpff_attachment_get_type: unable to retrieve attachment method.
export_handle_export_attachment: unable to retrieve attachment type.
Exporting email item 17 out of 17.
libpff_message_get_html_body_size: missing value data.
libpff_offsets_index_get_index_value_by_identifier: no recovered offsets index v
alues for identifier: 8032.
libpff_io_handle_read_descriptor_data_list: unable to find offset index value id
entifier: 8032.
libpff_table_read: unable to read descriptor: 1682 data: 8032 list.
libpff_item_values_read: unable to read table.
libpff_message_initialize_sub_item_recipients: unable to read recipients local d
escriptor identifier: 1682.
libpff_message_determine_recipients: unable to create sub item recipients.
libpff_message_get_recipients: unable to determine recipients.
export_handle_export_recipients: unable to retrieve recipients.
libpff_message_get_html_body_size: missing value data.
Exporting attachment 1 out of 2.
libpff_offsets_index_get_index_value_by_identifier: no recovered offsets index v
alues for identifier: 8090.
libpff_local_descriptors_tree_read: unable to retrieve offset index value identi
fier: 8090.
libpff_table_read: unable to read local descriptors tree with identifier: 8090.
libpff_item_values_read: unable to read table.
libpff_item_values_get_record_entry_by_type: unable to read item values.
libpff_internal_item_get_entry_value_32bit_integer: unable to retrieve record en
try: 0x04I32x 0x3705.
libpff_attachment_get_type: unable to retrieve attachment method.
export_handle_export_attachment: unable to retrieve attachment type.
Exporting attachment 2 out of 2.
libpff_offsets_index_get_index_value_by_identifier: no recovered offsets index v
alues for identifier: 8250.
libpff_local_descriptors_tree_read: unable to retrieve offset index value identi
fier: 8250.
libpff_table_read: unable to read local descriptors tree with identifier: 8250.
libpff_item_values_read: unable to read table.
libpff_item_values_get_record_entry_by_type: unable to read item values.
libpff_internal_item_get_entry_value_32bit_integer: unable to retrieve record en
try: 0x04I32x 0x3705.
libpff_attachment_get_type: unable to retrieve attachment method.
export_handle_export_attachment: unable to retrieve attachment type.

Export completed.
////////////////////////////////////////////////////////////////////////////////
The Sample.pst.export folder contains :
![export](https://user-images.githubusercontent.com/9929608/34407368-17ed64a0-ebe4-11e7-8360-024fefc6e715.JPG)
The Sample.pst.recovered folder contains
![recovered](https://user-images.githubusercontent.com/9929608/34407376-263dd954-ebe4-11e7-8e7b-a9d948598182.JPG)
///////////////////////////////////////////////////////////////////////////////
Am I doing it in wrong way ? please help.

**Comment by joachimmetz** [comment]
which version of libpff?

**Comment by kumartvm** [comment]
libpff-experimental-20161119

**Comment by joachimmetz** [comment]
I finally got some time to work on libpff. @kumartvm any chance you can share Sample.pst so I can have a closer look?

**Comment by joachimmetz** [comment]
No additional response from reporter closing issue
