### ISSUE TITLE
Extract .msg files from .pst

### ISSUE THREAD

**Issue by denisb411** [libyal/libpff#53]
I successfully extracted the messages from my .pst but I wanted to keep the original format of the message (.msg). How can I keep the .msg format from the .pst and save to disk?
The help(pypff.message) doesn't expecify anything about.

```
import pypff
pst_file = './backup.pst'
opst = pypff.open(pst_file)
root = opst.get_root_folder()

for folder in root.sub_folders:
    for message in folder.sub_messages:
        print(message.subject)
```

**Comment by joachimmetz** [comment]
Msg is not the same format. Have a look at the msdn documentation what office msg files are.

**Comment by joachimmetz** [comment]
Assuming questions have been answered
