### ISSUE TITLE
Pypff: Extract each message from a conversation

### ISSUE THREAD

**Issue by Vonisoa** [libyal/libpff#54]
I have a .pst file and I want to get messages in this file. But the trouble is that my .pst file strucutre is like a conversation so all the conversation is considered as a body message.
I use this code [https://github.com/PacktPublishing/Learning-Python-for-Forensics/blob/master/Chapter%2011/pst_indexer.py](pst_indexer.py)

So how can I get each message with pypff?

**Comment by joachimmetz** [comment]
pypff is work in progress, also see: https://github.com/libyal/libpff/issues/2

could you indicate what part of the https://github.com/PacktPublishing/Learning-Python-for-Forensics you are using?

Also that code appears to be copyrighted I cannot help you improve that code unless it has an Open Source license.

**Comment by Vonisoa** [comment]
Thanks for your answer.

**Comment by joachimmetz** [comment]
Assuming questions have been answered
