### ISSUE TITLE
libpff.h has wrong libpff_record_entry_get_value_utf16_string() prototype

### ISSUE THREAD

**Issue by thims** [libyal/libpff#6]
First argument has to be:
libpff_record_entry_t *record_entry

**Comment by thims** [comment]
And even more! libpff_record_entry_get_value_utf16_string_size() reports incorrect string size (+2 bytes) for LIBPFF_ENTRY_TYPE_MESSAGE_SUBJECT for any Outlook 2013 OST.

In a code like that:

    libpff_error_t *error = nullptr;
    libpff_record_set_t *set = nullptr;
    libpff_item_get_record_set_by_index(m_Item, 0, &set, &error);

    libpff_record_entry_t *entry = nullptr;
    libpff_record_set_get_entry_by_type(set, LIBPFF_ENTRY_TYPE_MESSAGE_SUBJECT, LIBPFF_VALUE_TYPE_STRING_UNICODE, &entry, 0, &error);

    size_t l = 0;
    libpff_record_entry_get_value_utf16_string_size(entry, &l, &error);
    if (l > 0) libpff_record_entry_get_value_utf16_string(entry, (uint16_t*)buffer, l, &error);

I get "l" 2 bytes bigger than needed, also resulting buffer contains extra two bytes (binary) IN THE BEGINNING of the string.

**Comment by thims** [comment]
One more interesting thing: it retrieves incorrect string for all folders except "Sync Issues" (which is a local folder in Outlook).

**Comment by joachimmetz** [comment]
I"ll have a look when time permits.

**Comment by joachimmetz** [comment]
Issue fixed note that these functions are still under development as part of an API rework.
