### ISSUE TITLE
Runtime problems

### ISSUE THREAD

**Issue by StrongJava** [libyal/libpff#7]
I'm on OS X (10.10.2) with python2.7, and tried the alpha version which gave me a runtime error. I've now built/installed the development version, but it crashes python.  Here is the crash report: http://pastebin.com/Q1m2vR18

I'm hoping to get this working and to possibly contribute to the python bindings.  I'm new to c but may be able to contribute some.

Thanks for any help.

**Comment by StrongJava** [comment]
Upgraded system to python35, and now get:

Traceback (most recent call last):
  File "./testpypff.py", line 6, in <module>
    import pypff, sys
ImportError: dynamic module does not define init function (PyInit_pypff)

**Comment by joachimmetz** [comment]
Python 3 support is still WIP as indicated in: https://github.com/libyal/libpff/blob/master/README

> I'm on OS X (10.10.2) with python2.7, and tried the alpha version which gave me a runtime error.

Do you have a Python.org version installed on your system besides the OS X versions of Python?

**Comment by joachimmetz** [comment]
No update from OP, closing issue.

**Comment by StrongJava** [comment]
I apologize for not having replied to your question. My interest in this got pushed aside due to other project requirements. 

I have python34 from MacPorts installed.
