### ISSUE TITLE
patch for manpage warnings

### ISSUE THREAD

**Issue by rhash** [libyal/libpff#72]
Hello,

here are two patches from [libpff Debian package](https://salsa.debian.org/pkg-security-team/libpff) to fix man warnings in the manpages.

1. [fix-man-pages-pffexport-and-pffinfo.patch.gz](https://github.com/libyal/libpff/files/2722276/fix-man-pages-pffexport-and-pffinfo.patch.gz)
2. [fixes-for-libpff-manpage.patch.gz](https://github.com/libyal/libpff/files/2722275/fixes-for-libpff-manpage.patch.gz)

Please apply the patches, since the Debian Lintian tool treats man warnings as errors.

The second patch reduces multiple man warnings to the warning "can't break line".

One can test a manpage (e.g. libpff.3) for warnings using the following command:
~~~sh
     LC_ALL=en_US.UTF-8 MANROFFSEQ='' MANWIDTH=80 \
            man --warnings -E UTF-8 -l -Tutf8 -Z libpff.3 >/dev/null
~~~

Thanks

**Comment by joachimmetz** [comment]
Thx for the patch, I'll have a look when time permits to integrate the proposed changes.

**Comment by joachimmetz** [comment]
Updated manpage, added tests to validate them using the proposed method.
https://github.com/libyal/libpff/commit/8d82a689417abe9c9aa272fd7782faea8c542393

**Comment by joachimmetz** [comment]
https://lintian.debian.org/tags/manpage-has-errors-from-man.html

**Comment by joachimmetz** [comment]
Still some issues:
```
     int
     libpff_file_get_root_item(libpff_file_t *file, libpff_item_t **root_item,
<standard input>:134: warning [p 4, 5.0i]: can't break line
<standard input>:136: warning [p 4, 5.7i]: can't break line
<standard input>:138: warning [p 4, 6.3i]: can't break line
         libpff_error_t **error);
```

**Comment by joachimmetz** [comment]
https://www.gnu.org/software/groff/manual/html_node/Manipulating-Hyphenation.html

**Comment by joachimmetz** [comment]
Consider not using `.Ft` and `.Fn` e.g.
```
.P
.B void opj_setup_encoder(opj_cinfo_t *\fIcinfo\fB, opj_cparameters_t *\fIparams\fB, opj_image_t *\fIimage\fB);
```

**Comment by joachimmetz** [comment]
@rhash any idea/context on why man/groff is still complaining about `can't break line`?

**Comment by joachimmetz** [comment]
Regarding fix-man-pages-pffexport-and-pffinfo.patch.gz it looks like `.Ar source` might be a better replacement.

https://www.freebsd.org/cgi/man.cgi?query=mdoc.samples
