### ISSUE TITLE
multiple mistypes

### ISSUE THREAD

**Issue by rhash** [libyal/libpff#73]
Libpff release 20180714 contains two mistypes. Here is a patch from Debian libpff package for the release tarball:
[01-fix-spelling-binary.patch.gz](https://github.com/libyal/libpff/files/2723473/01-fix-spelling-binary.patch.gz)

The patch replaces:
* 'intialize' -> 'initialize'
* 'retreive' -> 'retrieve'

The directories/libraries affected: libbfio, libcdata, libcsplit, libfvalue, pfftools.

**Comment by joachimmetz** [comment]
Thx for the patch, though I see that some of these typo are in dependencies not in the libpff source. I'll make the changes there instead.

**Comment by joachimmetz** [comment]
* libbfio
* libcdata
* libcsplit
* libfvalue
* pfftools

**Comment by joachimmetz** [comment]
Changes made to the affected projects, closing issue.
