### ISSUE TITLE
Python: invalid pst file signature

### ISSUE THREAD

**Issue by Elmetayer** [libyal/libpff#76]
Hi,

I'm using libpff Python on Mac OS, and I'm trying to open a pst file archive that I've created on my work PC.
I get the error below, do you have any idea where this could come from ?

OSError                                   Traceback (most recent call last)
<ipython-input-10-f21be0d1e160> in <module>()
      1 pff_file = pypff.file()
----> 2 pff_file.open("Mail/Archive mails 20140818.pst", mode="r")
      3 pff_file.close()

OSError: pypff_file_open: unable to open file. libpff_io_handle_read_file_header: invalid file signature. libpff_file_open_read: unable to read file header. libpff_file_open_file_io_handle: unable to read from file handle. libpff_file_open: unable to open file: Mail/Archive mails 20140818.pst.

Thanks !

**Comment by joachimmetz** [comment]
can you hexdump the first 64 bytes of the pst? the library is telling you it cannot find the format signature it expects. A common issue with pst files are copy issues.

**Comment by Elmetayer** [comment]
Here it is:

0000000 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00

0000010 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00

0000020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00

0000030 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00

0000040

Le mer. 13 févr. 2019 à 06:19, Joachim Metz <notifications@github.com> a
écrit :

**Comment by joachimmetz** [comment]
yeah, as I suspected. The data is corrupt and technically not a PST file.

**Comment by Elmetayer** [comment]
Thanks ! this is strange, it was created as an archive in outlook as the
rest of my pst files (which are processed ok), and is still readable in
outlook

Le ven. 15 févr. 2019 à 17:00, Joachim Metz <notifications@github.com> a
écrit :

**Comment by joachimmetz** [comment]
Likely an I/O sync error. This happened frequently to me in the past, likely a remove-able media sync did not happen before disconnecting.

> and is still readable in outlook

are you sure the empty file is readable by outlook? or are you looking at the original?

**Comment by Elmetayer** [comment]
Yes it’s readable as the others I have ... I’ll create again this archive

Le dim. 17 févr. 2019 à 17:08, Joachim Metz <notifications@github.com> a
écrit :

**Comment by joachimmetz** [comment]
Strange since MS-PST states:
```
dwMagic (4 bytes): MUST be "{ 0x21, 0x42, 0x44, 0x4E } ("!BDN")"
```

**Comment by TonyD-evOps** [comment]
Hi,

I have a PST file (20Go) that is completely corrupted. The first 64 bytes of the header are 00 even the rest of the file. I would like to know if it could be possible to add dwMagic and the help of some kind of "magic tool" to rebuild the file or will it be impossible and the file is dead.... ? 

Thank you !

**Comment by joachimmetz** [comment]
@TonyD-evOps this is NOT a PST file, this is 0-byte data, which basically means you have no PST data.

**Comment by TonyD-evOps** [comment]
But the file indicates a size of 20Go in the explorer ....

**Comment by joachimmetz** [comment]
> But the file indicates a size of 20Go in the explorer ....

And your point is?
