### ISSUE TITLE
Retrieving Recipients with Python Bindings

### ISSUE THREAD

**Issue by johuellm** [libyal/libpff#77]
Hey everyone,

the tool pffexport retrieves the recipients of a message and exports them via ``export_handle_export_recipients``. I cannot find anything to export the recipients with the Python bindings. The ``sub_items`` collection is always empty. Is it just not implemented yet, or am I missing something?

cheers

**Comment by joachimmetz** [comment]
These are still WIP also see: https://github.com/libyal/libpff/issues/2
