### ISSUE TITLE
Get real email address from Active Directory Object

### ISSUE THREAD

**Issue by jalevin** [libyal/libpff#79]
When using pffexport, there are internal emails from an Active Directory/Exchange domain that produce active directory strings as the email address. I've looked into ways to rebuild the string, but some pst's include the domain and other's done- for example

eg1:  /O=FIRST ORGANIZATION/OU=First Administrative Group/cn=Recipients/cn=jalevin
where there is no domain or TLD

eg2: /O=levinology/OU=FIRST ADMINISTRATIVE GROUP/CN=RECIPIENTS/CN=jalevin
where levinology is the domain, but no TLD listed.

Is there a way to get the actual email string or infer the correct domain?

**Comment by joachimmetz** [comment]
> Is there a way to get the actual email string or infer the correct domain?

What do you mean with "actual email string"?

I opt to check your Exchange server for the corresponding X.500 address.

**Comment by jalevin** [comment]
I was curious if there was a way to get the email address like "jeff@levinology.com" info out of libpff. I'm processing .psts that are provided and do not have access to the X.500.

**Comment by joachimmetz** [comment]
> Is it correct that a PST would only contain one domain name or would that be impossible to tell without looking at the Exchange configuration?

I do not know. These are Exchange/Outlook internals questions. A PST is nothing more than a MAPI Exchange/Outlook value database. How to interpret them depends on how they are used.

**Comment by jalevin** [comment]
Thank you

**Comment by joachimmetz** [comment]
Assuming questions have been answered, closing issue.
