### ISSUE TITLE
Return more details about attachments

### ISSUE THREAD

**Issue by wyllys66** [libyal/libpff#81]
It would be very useful to be able to get more details about attachments (if available). Specifically, the original filename of the attachment and content-disposition (inline vs attached).

**Comment by joachimmetz** [comment]
In what context, do you mean from pffexport?

**Comment by wyllys66** [comment]
Mostly interested in the python bindings.  I'd like a python method or property to return the original filename of the attachment if it was found.

**Comment by wyllys66** [comment]
LIBPFF_ENTRY_TYPE_ATTACHMENT_FILENAME_SHORT and LIBPFF_ENTRY_TYPE_ATTACHMENT_FILENAME_LONG are defined, but not used anywhere. I would think they could be used in libpff_attachment.c when parsing the data to capture the filename.

**Comment by wyllys66** [comment]
It looks like someone submitted a pull-request for this feature last year but never followed up after the tests failed:

https://github.com/libyal/libpff/pull/69

Perhaps someone could pick this up and complete the merge?

**Comment by joachimmetz** [comment]
> Perhaps someone could pick this up and complete the merge?

I'll have a look when time permits. Closing issue
