### ISSUE TITLE
Python Binding (On Windows)

### ISSUE THREAD

**Issue by apdullahyayik** [libyal/libpff#85]
I have successfully implemented binding on Ubuntu 19.10, however at windows 10 there exist an error after the commands below.
Any help will be appreciated.

Thanks

Commands:

cd libpff
./synclibs.sh
./autogen.sh
./configure --prefix /usr/ --with-python –with-python3
Error:
to use local version... (cached) auto-detect
./configure: line 15879: syntax error near unexpected token newline'
./configure: line 15879: PKG_CHECK_MODULES('

**Comment by joachimmetz** [comment]
1. don't build from git directly unless you want to develop libpff (see: https://github.com/libyal/libpff/wiki/Building#read-first)
2. provide more detail about your build environment (Cygwin, MinGW)

The error says your build environment is missing the pkg-config m4 macros

**Comment by joachimmetz** [comment]
No additional response from reporter closing issue.
