### ISSUE TITLE
Implement write support

### ISSUE THREAD

**Issue by lattera** [libyal/libpff#86]
I'm working on an open source project, [The Migrationator](https://github.com/g2-inc/migrationator). It needs to be able to write PST files (merge multiple PST files into one).

I plan to investigate adding missing write support in libpff. This ticket is to track the progress of that investigation.

If there's any [non-xkcd pointers](https://imgs.xkcd.com/comics/pointers.png) anyone can pass along to me, that'd be very much appreciated. :-)

**Comment by joachimmetz** [comment]
@lattera please move this issue to g2-inc/migrationator. Unless you have PRs that actually implement write support this issue does not belong here.

**Comment by lattera** [comment]
I was under the impression that GitHub Issues were different than GitHub PRs.

However, I'll close this ticket as you wish. I guess without this ticket, I'll just maintain radio silence until I have a patch fully ready.

**Comment by joachimmetz** [comment]
> I was under the impression that GitHub Issues were different than GitHub PRs.

yes and no, PRs are tracked by issues

> I guess without this ticket, I'll just maintain radio silence until I have a patch fully ready.

I would recommend to

1. do you "planning" work first, maybe track this in g2-inc/migrationator.
2. once you have a plan, drop me an email to discuss your plan
3. once you start executing on your plan, we can create an issue in this project to track progress

**Comment by lattera** [comment]
For now I've forked the repo here: https://git-01.md.hardenedbsd.org/shawn.webb/libpff

I'll reach out to you when I have more to report. If I have any questions, do you mind if I bug you via email?

**Comment by joachimmetz** [comment]
> If I have any questions, do you mind if I bug you via email?

Email is fine.
