### ISSUE TITLE
Change file system date and time values for exported emails folder/files and attachments

### ISSUE THREAD

**Issue by djRicky** [libyal/libpff#90]
Please when exporting mails I'd like to preserve the original datetime of the message and the original file datetime of each attachments rather than the extracted datetime. If it's possible.

Thanks

**Comment by joachimmetz** [comment]
@djRicky can you be a more explanatory of what you are asking.

Are you referring to the date and time values of the exported attachment file on your file system? Or something else?

**Comment by djRicky** [comment]
Every email inside the PST has its own date and time (for example sent or received). Also, every file in the attachments, has created/modified date and time. When you export, all date and times of every exported file has the exported date and time, not their original values. I asking about touching those files with their original date and time.

**Comment by joachimmetz** [comment]
> I asking about touching those files with their original date and time.

Doing this in a cross platform reliable way is unlikely to be straightforward.

Also this is outside the of scope of the project. The main focus of the project is to provide a library the tools are intended for basic usage of the library. If you want this functionality I recommend writing your own platform specific tool that uses the library.

Marking this issue as infeasible.

**Comment by djRicky** [comment]
Thanks for your fast answer. I forgot the cross platform issue. You are right. It's a complex thing.
But if the library can export the date and time value, only the cross platform problem will remain.

**Comment by joachimmetz** [comment]
If these are MAPI values of the attachment item, the library should already be able to export them.

**Comment by joachimmetz** [comment]
No additional response from reporter closing issue.
