### ISSUE TITLE
Improving recovery methodology

### ISSUE THREAD

**Issue by zy-ph** [libyal/libpff#91]
I am trying to recover deleted items from an ost file, but I get only one item. Other tools can recover a lot more.
[Link to log file](https://www.dropbox.com/s/34pjb32sogmo08x/log.zip?dl=0) from 'pffexport -v -m recovered [name hidden].ost >log.txt 2>&1'

pffinfo 20200808

Personal Folder File information:
        File size:              650616832 bytes
        File content type:      Offline Storage Tables (OST)
        File type:              64-bit with 4k page
        Encryption type:        none

Message store:
        Password checksum:      N/A

Note I limited the node (footer) data to 32 bytes

**Comment by joachimmetz** [comment]
> Other tools can recover a lot more.

It is open source, if you want to help improve the recovery methodology go ahead

**Comment by joachimmetz** [comment]
No suggestions for improving recovery method from original reporter, closing
