### ISSUE TITLE
Question: Check if a message has been readed

### ISSUE THREAD

**Issue by Xachap** [libyal/libpff#93]
Hi,

I've installed pypff for python3, and I want to know if there is a way to check if an email has been read. I'm working with _.ost_ files from Outlook local app for Windows. Thank you in advance.

Best regards,
Jesús

**Comment by joachimmetz** [comment]
The Python bindings are still under development. See https://github.com/libyal/libpff/issues/2.

You'll need to find the corresponding MAPI value. See https://github.com/libyal/libfmapi/blob/master/documentation/MAPI%20definitions.pdf

Which is likely PidTagMessageFlags
