### ISSUE TITLE
Question: Reading signed emails

### ISSUE THREAD

**Issue by Nick-P-Orr** [libyal/libpff#95]
I'm developing an app to read emails from a PST and export them as individual HTML files. I'm using PyPFF with the following code:

```
pst_file = pypff.file()
pst_file.open(selectedPST)

root = pst_file.get_root_folder()

for folder in root.sub_folders:
    for sub in folder.sub_folders:
        for message in sub.sub_messages:
            print(message.get_html_body())
```
but when I come across a signed email, it returns 'none'. Is there any way to read them?

PyWIN32 is able to read these signed emails, but because of another issue (it strips a <META> tag containing info I need), I can't totally rely on it.

**Comment by joachimmetz** [comment]
In which MAPI property is the signed email body stored?

**Comment by Nick-P-Orr** [comment]
From my understanding it's a smime.p7m attachment but as for a MAPI property I'm unsure.

http://www.cryptigo.eu/FAQ/

**Comment by joachimmetz** [comment]
You'll likely need to read the attachment then not the HTML body MAPI property. Have a look at https://github.com/libyal/libfmapi/blob/main/documentation/MAPI%20definitions.pdf

Also note that pypff is work-in-progress https://github.com/libyal/libpff/issues/2

**Comment by Nick-P-Orr** [comment]
Thank you for the pointers 😁

**Comment by joachimmetz** [comment]
Ack, I'll consider the question answered then.
