### ISSUE TITLE
Question on maximum number of record sets per item

### ISSUE THREAD

**Issue by jengelh** [libyal/libpff#97]
`libpff_item_get_number_of_record_sets(i, &n, NULL)` always appears to yield at most one record set all the time, that is, n <= 1.
`export_handle.c:export_handle_get_folder_name:13215` (as of 996825578bf5c36e8c992d6c81c33902fdd0f206) even passes a hardcoded `0` as the record set index to `export_handle_item_create_value_string_by_type`, which further suggests that PFF items only ever have one record set. Is this indeed the case? If so, wouldn't record set index arguments be redundant, as well as the item_get_number_of_record_sets function?

**Comment by joachimmetz** [comment]
> which further suggests that PFF items only ever have one record set. Is this indeed the case?

no, there are certain types of items that can have more than 1 record sets such as the "attachments item" or "recipients item"
